export const POST_DATA = "POST_DATA";
export const CATEGORY_DATA = "CATEGORY_DATA";
export const BRAND_DATA = "BRAND_DATA";
export const PRODUCT_DATA = "PRODUCT_DATA";
export const SUB_CATEGORY_LIST = "SUB_CATEGORY_LIST";
export const SUB_CHILD_CATEGORY_LIST = "SUB_CHILD_CATEGORY_LIST";
export const UPDATE_PRODUCT_FORM_DATA = "UPDATE_PRODUCT_FORM_DATA";
export const PRODUCT_IMAGE_DATA = "PRODUCT_IMAGE_DATA";
