export const POST_DATA = "POST_DATA";
export const CATEGORY_DATA_CP = "CATEGORY_DATA_CP";
export const BRAND_DATA = "BRAND_DATA";
export const PRODUCT_DATA_CP = "PRODUCT_DATA_CP";
export const PRODUCT_DETAILS_DATA_CP = "PRODUCT_DETAILS_DATA_CP";
export const SUB_CATEGORY_LIST = "SUB_CATEGORY_LIST";
export const SUB_CHILD_CATEGORY_LIST = "SUB_CHILD_CATEGORY_LIST";



